const fs = require('fs');

const dialogPath = 'D:/projects/daadah/daad-builder-ui/src/components/ImageDialog.tsx';
let content = fs.readFileSync(dialogPath, 'utf8');

// Update handleSave to match new Location type structure
content = content.replace(
  `  const handleSave = () => {
    if (!sourceImage) {
      onSave(undefined);
    } else {
      onSave({
        sourceData: sourceImage,
        scrData: undefined, // Will be generated by backend
        yPosition,
        height,
      });
    }
    onClose();
  };`,
  `  const handleSave = () => {
    if (!sourceImage) {
      onSave(undefined);
    } else {
      onSave({
        sourceData: sourceImage,
        yPosition,
        height,
        // platformImages will be generated by backend during export
      });
    }
    onClose();
  };`
);

fs.writeFileSync(dialogPath, content);
console.log('Fixed ImageDialog save handler for new Location type');
