const fs = require('fs');

const newContent = `import { useState } from "react";
import { Location } from "../types/daad";
import { PLATFORM_LIST, PlatformId, PlatformSpec } from "../types/platforms";

interface ImageDialogProps {
  location: Location;
  onClose: () => void;
  onSave: (image: Location["image"]) => void;
}

export default function ImageDialog({ location, onClose, onSave }: ImageDialogProps) {
  const [sourceImage, setSourceImage] = useState<string | null>(
    location.image?.sourceData || null
  );
  const [yPosition, setYPosition] = useState(location.image?.yPosition || 0);
  const [height, setHeight] = useState(location.image?.height || 128);
  const [selectedPlatform, setSelectedPlatform] = useState<PlatformId>("zx_spectrum");

  const currentPlatform: PlatformSpec = PLATFORM_LIST.find(p => p.id === selectedPlatform) || PLATFORM_LIST[0];

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = () => {
      setSourceImage(reader.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleSave = () => {
    if (!sourceImage) {
      onSave(undefined);
    } else {
      onSave({
        sourceData: sourceImage,
        scrData: undefined, // Will be generated by backend
        yPosition,
        height,
      });
    }
    onClose();
  };

  const handleRemove = () => {
    setSourceImage(null);
    onSave(undefined);
    onClose();
  };

  const previewWidth = currentPlatform.resolution.width * 2;
  const previewHeight = currentPlatform.resolution.height * 2;
  const clampedHeight = Math.min(height, currentPlatform.resolution.height);

  return (
    <div
      className="dialog-overlay"
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
      }}
      onClick={onClose}
    >
      <div
        className="dialog-content"
        style={{
          backgroundColor: "var(--bg-dark)",
          border: "2px solid var(--green-bright)",
          padding: 24,
          maxWidth: 800,
          width: "90%",
          maxHeight: "90vh",
          overflow: "auto",
          fontFamily: "'Share Tech Mono', monospace",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{ marginBottom: 24 }}>
          <h2 style={{ color: "var(--green-bright)", margin: 0, marginBottom: 8 }}>
            IMAGE MANAGER
          </h2>
          <p style={{ color: "var(--text-dim)", margin: 0 }}>
            Location: {location.name || \`Room \${location.id}\`}
          </p>
        </div>

        {/* Platform Selector */}
        <div className="card" style={{ marginBottom: 16 }}>
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label">Target Platform</label>
            <select
              value={selectedPlatform}
              onChange={(e) => setSelectedPlatform(e.target.value as PlatformId)}
              style={{
                display: "block",
                width: "100%",
                padding: 8,
                backgroundColor: "var(--bg-darker)",
                border: "1px solid var(--green-dim)",
                color: "var(--text-primary)",
                fontFamily: "'Share Tech Mono', monospace",
                fontSize: 14,
              }}
            >
              {PLATFORM_LIST.map((platform) => (
                <option key={platform.id} value={platform.id}>
                  {platform.displayName}
                </option>
              ))}
            </select>
            <p style={{ fontSize: 12, color: "var(--text-dim)", marginTop: 4 }}>
              {currentPlatform.resolution.width}×{currentPlatform.resolution.height}px • {currentPlatform.paletteSize} colors
              {currentPlatform.restrictions.description && \` • \${currentPlatform.restrictions.description}\`}
            </p>
          </div>
        </div>

        {/* Platform Preview */}
        <div style={{ marginBottom: 24 }}>
          <div
            style={{
              width: previewWidth,
              height: previewHeight,
              backgroundColor: "#000",
              border: "2px solid var(--green-dim)",
              position: "relative",
              margin: "0 auto",
            }}
          >
            {/* Screen area (scaled 2x) */}
            <div
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                width: previewWidth,
                height: previewHeight,
                display: "flex",
                flexDirection: "column",
              }}
            >
              {/* Image area */}
              <div
                style={{
                  flex: \`0 0 \${(clampedHeight / currentPlatform.resolution.height) * previewHeight}px\`,
                  backgroundColor: "#000",
                  position: "relative",
                  overflow: "hidden",
                }}
              >
                {sourceImage && (
                  <img
                    src={sourceImage}
                    alt="Preview"
                    style={{
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      imageRendering: "pixelated",
                    }}
                  />
                )}
                {!sourceImage && (
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      height: "100%",
                      color: "var(--text-dim)",
                      fontSize: 14,
                    }}
                  >
                    No image selected
                  </div>
                )}
              </div>

              {/* Text/Parser area */}
              <div
                style={{
                  flex: 1,
                  backgroundColor: "#000",
                  padding: 8,
                  fontSize: 12,
                  color: "var(--green-bright)",
                  fontFamily: "monospace",
                  lineHeight: 1.2,
                }}
              >
                <div>&gt; {location.description || "Room description..."}</div>
                <div style={{ marginTop: 8, color: "var(--text-dim)" }}>
                  You can see: ...
                </div>
                <div style={{ marginTop: 8 }}>
                  <span style={{ color: "var(--green-bright)" }}>&gt; </span>
                  <span className="cursor-blink">_</span>
                </div>
              </div>
            </div>

            {/* Dimension overlay */}
            <div
              style={{
                position: "absolute",
                top: 4,
                right: 4,
                backgroundColor: "rgba(0, 0, 0, 0.7)",
                padding: "4px 8px",
                fontSize: 10,
                color: "var(--green-bright)",
                border: "1px solid var(--green-dim)",
              }}
            >
              {currentPlatform.resolution.width}×{currentPlatform.resolution.height} px
            </div>
          </div>

          <div style={{ textAlign: "center", marginTop: 8, fontSize: 12, color: "var(--text-dim)" }}>
            {currentPlatform.displayName} Screen Preview (2x scale)
          </div>
        </div>

        {/* Controls */}
        <div className="card" style={{ marginBottom: 16 }}>
          <div className="form-group">
            <label className="form-label">Image File</label>
            <input
              type="file"
              accept="image/png,image/bmp,image/gif,image/jpeg"
              onChange={handleFileSelect}
              style={{
                display: "block",
                width: "100%",
                padding: 8,
                backgroundColor: "var(--bg-darker)",
                border: "1px solid var(--green-dim)",
                color: "var(--text-primary)",
                fontFamily: "'Share Tech Mono', monospace",
                fontSize: 14,
              }}
            />
            <p style={{ fontSize: 12, color: "var(--text-dim)", marginTop: 4 }}>
              Image will be converted to {currentPlatform.resolution.width}×{clampedHeight}px with {currentPlatform.displayName} palette
            </p>
          </div>

          <div className="form-group">
            <label className="form-label">Image Height: {clampedHeight}px</label>
            <input
              type="range"
              min="32"
              max={currentPlatform.resolution.height}
              step="8"
              value={clampedHeight}
              onChange={(e) => setHeight(Number(e.target.value))}
              style={{ width: "100%" }}
            />
            <p style={{ fontSize: 12, color: "var(--text-dim)", marginTop: 4 }}>
              Remaining space for text: {currentPlatform.resolution.height - clampedHeight}px
            </p>
          </div>
        </div>

        {/* Color Palette Reference */}
        {currentPlatform.palette && (
          <div style={{ marginBottom: 24 }}>
            <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 8 }}>
              {currentPlatform.displayName} Palette ({currentPlatform.paletteSize} colors):
            </div>
            <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
              {currentPlatform.palette.map((color, index) => (
                <div
                  key={index}
                  style={{
                    width: 24,
                    height: 24,
                    backgroundColor: color,
                    border: "1px solid var(--green-dim)",
                  }}
                  title={color}
                />
              ))}
            </div>
            <p style={{ fontSize: 11, color: "var(--text-dim)", marginTop: 8 }}>
              {currentPlatform.restrictions.description}
            </p>
          </div>
        )}

        {/* Action Buttons */}
        <div style={{ display: "flex", gap: 12, justifyContent: "flex-end" }}>
          {sourceImage && (
            <button
              className="btn btn-secondary"
              onClick={handleRemove}
              style={{ backgroundColor: "var(--red-dark)" }}
            >
              Remove Image
            </button>
          )}
          <button className="btn btn-secondary" onClick={onClose}>
            Cancel
          </button>
          <button className="btn btn-primary" onClick={handleSave}>
            Save
          </button>
        </div>
      </div>
    </div>
  );
}
`;

fs.writeFileSync('D:/projects/daadah/daad-builder-ui/src/components/ImageDialog.tsx', newContent);
console.log('Updated ImageDialog with platform selector');
