use super::{game::*, types::*};

/// DAAD Code Generator
/// Converts visual game data into DAAD source code
pub struct DaadCodeGenerator;

impl DaadCodeGenerator {
    /// Generate complete DAAD source code from visual game (DSF format)
    pub fn generate(game: &DaadGame) -> String {
        let mut code = String::new();

        // Header with DSF markers
        code.push_str(&Self::generate_header(game));

        // System texts (STX)
        code.push_str(&Self::generate_system_texts());

        // Location texts (LTX)
        code.push_str(&Self::generate_locations(&game.locations));

        // Object texts (OTX)
        code.push_str(&Self::generate_objects(&game.objects));

        // Messages (MTX)
        code.push_str(&Self::generate_messages(&game.messages));

        // Connections (CON)
        code.push_str(&Self::generate_connections(&game.locations));

        // Vocabulary (VOC)
        code.push_str(&Self::generate_vocabulary(&game.vocabulary));

        // Object initial locations (OBJ)
        code.push_str(&Self::generate_object_locations(&game.objects));

        // Process tables (PRO 0-3)
        code.push_str(&Self::generate_processes(game));

        // End marker
        code.push_str("\n/END\n");

        code
    }

    fn generate_header(game: &DaadGame) -> String {
        format!(
            "; ========================================\n\
             ; {}\n\
             ; by {}\n\
             ; Version: {}\n\
             ; Generated by DAAD Bevy Builder (DSF Format)\n\
             ; Target: DRC Compiler\n\
             ; ========================================\n\n\
             ; Initial player location\n\
             #define START_LOCATION 0\n\n",
            game.title, game.author, game.version
        )
    }

    fn generate_system_texts() -> String {
        String::from(
            "/STX ; System Texts\n\n\
             ; System messages (customize as needed)\n\
             You can't go that way.\n\
             You can't see that here.\n\
             You already have that.\n\
             You don't have that.\n\
             You can't do that.\n\
             Nothing happens.\n\
             OK.\n\
             You are carrying:\n\
             Nothing.\n\
             You can see:\n\
             Score: \n\
             Turns: \n\
             \n\n"
        )
    }

    fn generate_locations(locations: &[Location]) -> String {
        let mut code = String::from("/LTX ; Location Texts\n\n");

        for loc in locations {
            code.push_str(&format!("; Location {}: {}\n", loc.id, loc.name));
            if loc.is_dark {
                code.push_str("; DARK LOCATION\n");
            }
            // Use # for escape codes (DSF format)
            let description = loc.description.replace("\\", "#");
            code.push_str(&format!("{}\n\n", description));
        }

        code
    }

    fn generate_connections(locations: &[Location]) -> String {
        let mut code = String::from("/CON ; Connections\n\n");

        for loc in locations {
            if !loc.connections.is_empty() {
                code.push_str(&format!("; Location {} ({})\n", loc.id, loc.name));
                for conn in &loc.connections {
                    code.push_str(&format!(
                        "{} {}\n",
                        conn.direction.as_str().to_uppercase(),
                        conn.target_location
                    ));
                }
                code.push('\n');
            }
        }

        code
    }

    fn generate_objects(objects: &[Object]) -> String {
        let mut code = String::from("/OTX ; Object Texts\n\n");

        for obj in objects {
            code.push_str(&format!("; Object {}: {} {} (Weight: {})\n",
                obj.id, obj.adjective, obj.noun, obj.weight));
            // Use # for escape codes (DSF format)
            let description = obj.description.replace("\\", "#");
            code.push_str(&format!(
                "{} {} {}\n\n",
                obj.adjective, obj.noun, description
            ));
        }

        code
    }

    fn generate_object_locations(objects: &[Object]) -> String {
        let mut code = String::from("/OBJ ; Object Initial Locations\n\n");

        for obj in objects {
            let location_code = match obj.location {
                ObjectLocation::Limbo => 252,  // DAAD limbo location
                ObjectLocation::Carried => 254, // Carried by player
                ObjectLocation::Worn => 253,    // Worn by player
                ObjectLocation::Location(loc_id) => loc_id,
                ObjectLocation::Inside(_container_id) => 252,  // Objects in containers start in limbo, managed by rules
            };
            code.push_str(&format!(
                "{} ; Object {}: {} {}\n",
                location_code, obj.id, obj.adjective, obj.noun
            ));
        }

        code.push('\n');
        code
    }

    fn generate_messages(messages: &[String]) -> String {
        let mut code = String::from("/MTX ; Messages\n\n");

        for (i, msg) in messages.iter().enumerate() {
            code.push_str(&format!("; Message {}\n", i));
            code.push_str(&format!("{}\n\n", msg));
        }

        code
    }

    fn generate_vocabulary(vocab: &[VocabEntry]) -> String {
        let mut code = String::from("/VOC ; Vocabulary\n\n");

        let mut verbs: Vec<_> = vocab.iter().filter(|v| v.word_type == VocabType::Verb).collect();
        let mut nouns: Vec<_> = vocab.iter().filter(|v| v.word_type == VocabType::Noun).collect();
        let mut adjectives: Vec<_> = vocab
            .iter()
            .filter(|v| v.word_type == VocabType::Adjective)
            .collect();

        verbs.sort_by_key(|v| v.id);
        nouns.sort_by_key(|v| v.id);
        adjectives.sort_by_key(|v| v.id);

        if !verbs.is_empty() {
            code.push_str("; Verbs\n");
            for v in verbs {
                code.push_str(&format!("{} ; {}\n", v.word, v.id));
            }
            code.push('\n');
        }

        if !nouns.is_empty() {
            code.push_str("; Nouns\n");
            for n in nouns {
                code.push_str(&format!("{} ; {}\n", n.word, n.id));
            }
            code.push('\n');
        }

        if !adjectives.is_empty() {
            code.push_str("; Adjectives\n");
            for a in adjectives {
                code.push_str(&format!("{} ; {}\n", a.word, a.id));
            }
            code.push('\n');
        }

        code
    }

    fn generate_processes(game: &DaadGame) -> String {
        let mut code = String::new();

        // Generate each process table (DSF format requires > marker)
        for process_num in 0..4 {
            let process_type = ProcessTable::from_num(process_num);
            code.push_str(&format!(
                ">/PRO {} ; {}\n\n",
                process_num,
                process_type.description()
            ));

            // Get rules for this process
            let process_rules: Vec<_> = game
                .rules
                .iter()
                .filter(|r| r.process == process_type && r.enabled)
                .collect();

            for rule in process_rules {
                code.push_str(&Self::generate_rule(rule, game));
                code.push('\n');
            }
        }

        code
    }

    fn generate_rule(rule: &Rule, game: &DaadGame) -> String {
        let mut code = String::new();

        code.push_str(&format!("; Rule: {}\n", rule.name));

        // Generate conditions
        if !rule.conditions.is_empty() {
            for condition in &rule.conditions {
                code.push_str(&Self::generate_condition(condition, game));
                code.push('\n');
            }
        }

        // Generate actions
        if !rule.actions.is_empty() {
            for action in &rule.actions {
                code.push_str(&Self::generate_action(action, game));
                code.push('\n');
            }
        }

        code
    }

    fn generate_condition(condition: &Condition, game: &DaadGame) -> String {
        match &condition.condition_type {
            ConditionType::PlayerAt { location_id } => {
                let loc_name = game
                    .get_location(*location_id)
                    .map(|l| l.name.as_str())
                    .unwrap_or("???");
                format!("AT {} ; {}", location_id, loc_name)
            }
            ConditionType::PlayerNotAt { location_id } => {
                format!("NOTAT {}", location_id)
            }
            ConditionType::ObjectPresent { object_id } => {
                let obj_name = game
                    .get_object(*object_id)
                    .map(|o| o.name.as_str())
                    .unwrap_or("???");
                format!("PRESENT {} ; {}", object_id, obj_name)
            }
            ConditionType::ObjectNotPresent { object_id } => {
                format!("ABSENT {}", object_id)
            }
            ConditionType::ObjectCarried { object_id } => {
                let obj_name = game
                    .get_object(*object_id)
                    .map(|o| o.name.as_str())
                    .unwrap_or("???");
                format!("CARRIED {} ; {}", object_id, obj_name)
            }
            ConditionType::ObjectNotCarried { object_id } => {
                format!("NOTCARR {}", object_id)
            }
            ConditionType::ObjectWorn { object_id } => {
                format!("WORN {}", object_id)
            }
            ConditionType::ObjectAt {
                object_id,
                location_id,
            } => {
                format!("AT {} {}", object_id, location_id)
            }
            ConditionType::ObjectIsOpen { object_id } => {
                // Find flag for object open state (pattern: "object_X_open")
                let flag_name = format!("object_{}_open", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("EQ {} 1 ; {} is open", flag.id, flag_name)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ConditionType::ObjectIsClosed { object_id } => {
                let flag_name = format!("object_{}_open", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("EQ {} 0 ; {} is closed", flag.id, flag_name)
                } else {
                    format!("  ; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ConditionType::ObjectIsLocked { object_id } => {
                let flag_name = format!("object_{}_locked", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("EQ {} 1 ; {} is locked", flag.id, flag_name)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ConditionType::ObjectIsUnlocked { object_id } => {
                let flag_name = format!("object_{}_locked", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("EQ {} 0 ; {} is unlocked", flag.id, flag_name)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ConditionType::ObjectIsLit { object_id } => {
                let flag_name = format!("object_{}_lit", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("EQ {} 1 ; {} is lit", flag.id, flag_name)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ConditionType::PlayerInsideObject { object_id } => {
                let flag_name = format!("player_in_object_{}", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("EQ {} 1 ; Player inside object {}", flag.id, object_id)
                } else {
                    format!("; WARNING: Flag '{}' not found", flag_name)
                }
            }
            ConditionType::FlagEquals { flag_id, value } => {
                let flag_name = game
                    .get_flag(*flag_id)
                    .map(|f| f.name.as_str())
                    .unwrap_or("???");
                format!("EQ {} {} ; {}", flag_id, value, flag_name)
            }
            ConditionType::FlagNotEquals { flag_id, value } => {
                format!("NOTEQ {} {}", flag_id, value)
            }
            ConditionType::FlagGreaterThan { flag_id, value } => {
                format!("GT {} {}", flag_id, value)
            }
            ConditionType::FlagLessThan { flag_id, value } => {
                format!("LT {} {}", flag_id, value)
            }
            ConditionType::FlagGreaterOrEqual { flag_id, value } => {
                format!("GE {} {}", flag_id, value)
            }
            ConditionType::FlagLessOrEqual { flag_id, value } => {
                format!("LE {} {}", flag_id, value)
            }
            ConditionType::FlagZero { flag_id } => {
                format!("ZERO {}", flag_id)
            }
            ConditionType::FlagNotZero { flag_id } => {
                format!("NOTZERO {}", flag_id)
            }
            ConditionType::FlagsEqual { flag_id_a, flag_id_b } => {
                format!("; Compare flags {} and {}", flag_id_a, flag_id_b)
            }
            ConditionType::FlagInRange { flag_id, min, max } => {
                format!("; Check flag {} in range {}-{}", flag_id, min, max)
            }
            ConditionType::VerbIs { verb } => {
                format!("VERB {}", verb)
            }
            ConditionType::NounIs { noun } => {
                format!("NOUN {}", noun)
            }
            ConditionType::AdjectiveIs { adjective } => {
                format!("ADJECT {}", adjective)
            }
            ConditionType::IsFirstTurn => "TURNS 0".to_string(),
            ConditionType::TurnCountGreaterThan { turns } => {
                format!("TURNSGT {}", turns)
            }
            ConditionType::ScoreGreaterThan { score } => {
                format!("SCOREGT {}", score)
            }
            ConditionType::IsDark => "ISDARK".to_string(),
            ConditionType::All { conditions } => {
                let mut result = String::from("; ALL conditions:\n");
                for cond in conditions {
                    result.push_str(&Self::generate_condition(cond, game));
                    result.push('\n');
                }
                result
            }
            ConditionType::Any { conditions } => {
                let mut result = String::from("; ANY of these conditions (requires manual DAAD logic):\n");
                for cond in conditions {
                    result.push_str(&format!("; Option: {}\n", Self::generate_condition(cond, game)));
                }
                result
            }
            ConditionType::Not { condition } => {
                format!("; NOT: {}", Self::generate_condition(condition, game))
            }
        }
    }

    fn generate_action(action: &Action, game: &DaadGame) -> String {
        match &action.action_type {
            ActionType::ShowMessage { text } => {
                format!("MESSAGE \"{}\"", text)
            }
            ActionType::ShowLocationDescription => "DESC".to_string(),
            ActionType::ClearScreen => "CLS".to_string(),
            ActionType::GetObject { object_id } => {
                let obj_name = game
                    .get_object(*object_id)
                    .map(|o| o.name.as_str())
                    .unwrap_or("???");
                format!("GET {} ; {}", object_id, obj_name)
            }
            ActionType::DropObject { object_id } => {
                format!("DROP {}", object_id)
            }
            ActionType::WearObject { object_id } => {
                format!("WEAR {}", object_id)
            }
            ActionType::RemoveObject { object_id } => {
                format!("REMOVE {}", object_id)
            }
            ActionType::MoveObject {
                object_id,
                to_location,
            } => {
                let loc_num = to_location.to_daad_location();
                format!("PLACE {} {}", object_id, loc_num)
            }
            ActionType::SwapObjects { object_a_id, object_b_id } => {
                format!("SWAP {} {}", object_a_id, object_b_id)
            }
            ActionType::DestroyObject { object_id } => {
                format!("DESTROY {}", object_id)
            }
            ActionType::OpenObject { object_id } => {
                let flag_name = format!("object_{}_open", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("LET {} 1 ; Open object {}", flag.id, object_id)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ActionType::CloseObject { object_id } => {
                let flag_name = format!("object_{}_open", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("LET {} 0 ; Close object {}", flag.id, object_id)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ActionType::LockObject { object_id } => {
                let flag_name = format!("object_{}_locked", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("LET {} 1 ; Lock object {}", flag.id, object_id)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ActionType::UnlockObject { object_id } => {
                let flag_name = format!("object_{}_locked", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("LET {} 0 ; Unlock object {}", flag.id, object_id)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ActionType::LightObject { object_id } => {
                let flag_name = format!("object_{}_lit", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("LET {} 1 ; Light object {}", flag.id, object_id)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ActionType::ExtinguishObject { object_id } => {
                let flag_name = format!("object_{}_lit", object_id);
                if let Some(flag) = game.flags.iter().find(|f| f.name == flag_name) {
                    format!("LET {} 0 ; Extinguish object {}", flag.id, object_id)
                } else {
                    format!("; WARNING: Flag '{}' not found - add via Object Behavior Preset", flag_name)
                }
            }
            ActionType::EnterObject { object_id } => {
                format!("AUTOG {} ; Enter object (vehicle/container)", object_id)
            }
            ActionType::ExitObject { object_id } => {
                format!("AUTOD {} ; Exit object", object_id)
            }
            ActionType::SetFlag { flag_id, value } => {
                let flag_name = game
                    .get_flag(*flag_id)
                    .map(|f| f.name.as_str())
                    .unwrap_or("???");
                format!("LET {} {} ; {}", flag_id, value, flag_name)
            }
            ActionType::IncrementFlag { flag_id } => {
                format!("PLUS {} 1", flag_id)
            }
            ActionType::DecrementFlag { flag_id } => {
                format!("MINUS {} 1", flag_id)
            }
            ActionType::AddToFlag { flag_id, amount } => {
                format!("PLUS {} {}", flag_id, amount)
            }
            ActionType::SubtractFromFlag { flag_id, amount } => {
                format!("MINUS {} {}", flag_id, amount)
            }
            ActionType::ToggleFlag { flag_id } => {
                format!("; Toggle flag {} (requires DAAD logic)", flag_id)
            }
            ActionType::CopyFlag { from_flag_id, to_flag_id } => {
                format!("COPYFF {} {}", from_flag_id, to_flag_id)
            }
            ActionType::SetFlagToRandom { flag_id, max } => {
                format!("RANDOM {} {}", flag_id, max)
            }
            ActionType::MinFlag { flag_id, min_value } => {
                format!("; Clamp flag {} to minimum {}", flag_id, min_value)
            }
            ActionType::MaxFlag { flag_id, max_value } => {
                format!("; Clamp flag {} to maximum {}", flag_id, max_value)
            }
            ActionType::GoToLocation { location_id } => {
                let loc_name = game
                    .get_location(*location_id)
                    .map(|l| l.name.as_str())
                    .unwrap_or("???");
                format!("GOTO {} ; {}", location_id, loc_name)
            }
            ActionType::ShowPicture { picture_id } => {
                format!("PICTURE {}", picture_id)
            }
            ActionType::ClearPicture => {
                "PICTURE 255".to_string() // DAAD convention: 255 clears picture
            }
            ActionType::PlaySound { sound_id } => {
                format!("SOUND {}", sound_id) // Maluva extension
            }
            ActionType::PlayMusic { music_id } => {
                format!("MUSIC {}", music_id) // Maluva extension
            }
            ActionType::StopSound => {
                "SOUND 0".to_string() // DAAD convention: 0 stops sound
            }
            ActionType::EndTurn => "DONE".to_string(),
            ActionType::ContinueProcessing => "NOTDONE".to_string(),
            ActionType::SkipRules { count } => {
                format!("SKIP {}", count)
            }
            ActionType::AddScore { points } => {
                format!("SCORE {}", points)
            }
            ActionType::SubtractScore { points } => {
                format!("MINUS SCORE {}", points)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_empty_game() {
        let game = DaadGame::default();
        let code = DaadCodeGenerator::generate(&game);
        assert!(code.contains("/LTX"));
        assert!(code.contains("/OTX"));
        assert!(code.contains("/PRO 0"));
    }

    #[test]
    fn test_generate_simple_rule() {
        let mut game = DaadGame::default();
        let rule_id = game.add_rule("Test Rule", ProcessTable::Response);

        let rule = game.rules.get_mut(rule_id).unwrap();
        rule.conditions.push(Condition {
            id: 0,
            condition_type: ConditionType::PlayerAt { location_id: 0 },
        });
        rule.actions.push(Action {
            id: 0,
            action_type: ActionType::ShowMessage {
                text: "Hello!".to_string(),
            },
        });

        let code = DaadCodeGenerator::generate(&game);
        assert!(code.contains("AT 0"));
        assert!(code.contains("MESSAGE \"Hello!\""));
    }
}
