import { useState, useRef } from "react";
import { Location } from "../types/daad";
import { PLATFORM_LIST, PlatformId, PlatformSpec } from "../types/platforms";

interface ImageDialogProps {
  location: Location;
  onClose: () => void;
  onSave: (image: Location["image"]) => void;
}

export default function ImageDialog({ location, onClose, onSave }: ImageDialogProps) {
  const [sourceImage, setSourceImage] = useState<string | null>(
    location.image?.sourceData || null
  );
  const [originalImage, setOriginalImage] = useState<string | null>(
    location.image?.sourceData || null
  );
  const [yPosition, setYPosition] = useState(location.image?.yPosition || 0);
  const [height, setHeight] = useState(location.image?.height || 128);
  const [selectedPlatform, setSelectedPlatform] = useState<PlatformId>("zx_spectrum");
  const [isProcessing, setIsProcessing] = useState(false);
  const [analyzedPalette, setAnalyzedPalette] = useState<string[] | null>(null);
  const [showPaletteAnalyzer, setShowPaletteAnalyzer] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const currentPlatform: PlatformSpec = PLATFORM_LIST.find(p => p.id === selectedPlatform) || PLATFORM_LIST[0];

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = () => {
      const imageData = reader.result as string;
      setSourceImage(imageData);
      setOriginalImage(imageData); // Save original for reprocessing
    };
    reader.readAsDataURL(file);
  };

  const handleSave = () => {
    if (!sourceImage) {
      onSave(undefined);
    } else {
      onSave({
        sourceData: sourceImage,
        yPosition,
        height,
        // platformImages will be generated by backend during export
      });
    }
    onClose();
  };

  const handleRemove = () => {
    setSourceImage(null);
    setOriginalImage(null);
    onSave(undefined);
    onClose();
  };

  
  // Find closest color in platform palette
  const findClosestColor = (r: number, g: number, b: number, palette: string[]): string => {
    let minDistance = Infinity;
    let closestColor = palette[0];

    for (const color of palette) {
      const pr = parseInt(color.slice(1, 3), 16);
      const pg = parseInt(color.slice(3, 5), 16);
      const pb = parseInt(color.slice(5, 7), 16);

      const distance = Math.sqrt(
        Math.pow(r - pr, 2) +
        Math.pow(g - pg, 2) +
        Math.pow(b - pb, 2)
      );

      if (distance < minDistance) {
        minDistance = distance;
        closestColor = color;
      }
    }

    return closestColor;
  };

  // Apply platform palette to image
  const handleApplyPalette = async () => {
    if (!originalImage || !currentPlatform.palette) return;

    setIsProcessing(true);

    try {
      const img = new Image();
      img.src = originalImage; // Always process from original

      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });

      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      ctx.drawImage(img, 0, 0);
      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      const data = imageData.data;

      // Convert each pixel to closest palette color
      for (let i = 0; i < data.length; i += 4) {
        const r = data[i];
        const g = data[i + 1];
        const b = data[i + 2];

        const closestColor = findClosestColor(r, g, b, currentPlatform.palette);

        data[i] = parseInt(closestColor.slice(1, 3), 16);
        data[i + 1] = parseInt(closestColor.slice(3, 5), 16);
        data[i + 2] = parseInt(closestColor.slice(5, 7), 16);
      }

      ctx.putImageData(imageData, 0, 0);
      const processedImage = canvas.toDataURL('image/png');
      setSourceImage(processedImage);
    } catch (error) {
      console.error('Error applying palette:', error);
    } finally {
      setIsProcessing(false);
    }
  };

  // Generate full color space for a platform (e.g., all 512 colors for Atari ST)
  const generatePlatformColorSpace = (colorDepth: number): string[] => {
    const colors: string[] = [];

    if (colorDepth === 9) {
      // Atari ST: 512 colors (3-bit per RGB channel: 000-111 binary = 0-7 decimal)
      // Each channel: 0, 36, 73, 109, 146, 182, 219, 255 (8 levels)
      const levels = [0, 36, 73, 109, 146, 182, 219, 255];
      for (const r of levels) {
        for (const g of levels) {
          for (const b of levels) {
            colors.push(`#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`);
          }
        }
      }
    } else if (colorDepth === 12 && currentPlatform.id.startsWith('amstrad_cpc')) {
      // Amstrad CPC: 27 colors (3-level RGB)
      // Use the full 27-color palette
      return currentPlatform.palette || [];
    } else if (colorDepth === 12 && currentPlatform.id === 'amiga') {
      // Amiga: 4096 colors (4-bit per RGB channel)
      const levels = Array.from({length: 16}, (_, i) => i * 17); // 0, 17, 34, ..., 255
      for (const r of levels) {
        for (const g of levels) {
          for (const b of levels) {
            colors.push(`#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`);
          }
        }
      }
    } else if (colorDepth === 18) {
      // MS-DOS VGA: 262,144 colors (6-bit per RGB channel)
      // Sample every 4th value to keep it manageable (still 4096 colors sampled)
      const levels = Array.from({length: 16}, (_, i) => i * 17); // Sample 16 levels per channel
      for (const r of levels) {
        for (const g of levels) {
          for (const b of levels) {
            colors.push(`#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`);
          }
        }
      }
    }

    return colors;
  };

  // Check if platform benefits from palette analysis
  const canAnalyzePalette = (): boolean => {
    // Platforms with selectable palettes from larger color spaces
    const selectablePlatforms: PlatformId[] = [
      'atari_st',      // 16 from 512
      'amiga',         // 32 from 4096
      'msdos',         // 256 from 262K
      'amstrad_cpc_mode0', // 16 from 27
      'amstrad_cpc_mode1', // 4 from 27
    ];
    return selectablePlatforms.includes(currentPlatform.id);
  };

  // Analyze image colors and extract optimal palette (median cut algorithm)
  const analyzePalette = async (targetColors: number, constrainedPalette?: string[]): Promise<string[]> => {
    if (!originalImage) return [];

    return new Promise((resolve, reject) => {
      const img = new Image();
      img.src = originalImage;

      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          reject(new Error('Could not get canvas context'));
          return;
        }

        ctx.drawImage(img, 0, 0);
        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        const data = imageData.data;

        // Extract unique colors
        const colorMap = new Map<string, number>();
        for (let i = 0; i < data.length; i += 4) {
          const r = data[i];
          const g = data[i + 1];
          const b = data[i + 2];
          const a = data[i + 3];

          // Skip fully transparent pixels
          if (a < 128) continue;

          const key = `${r},${g},${b}`;
          colorMap.set(key, (colorMap.get(key) || 0) + 1);
        }

        // Convert to array of [r, g, b, count]
        let colors: [number, number, number, number][] = Array.from(colorMap.entries()).map(([key, count]) => {
          const [r, g, b] = key.split(',').map(Number);
          return [r, g, b, count];
        });

        // If we have a constrained palette (e.g., Amstrad CPC 27 colors or Atari ST 512 colors),
        // first map all image colors to the constrained palette
        if (constrainedPalette && constrainedPalette.length > 0) {
          const constrainedColorMap = new Map<string, number>();

          for (const [r, g, b, count] of colors) {
            const closestColor = findClosestColor(r, g, b, constrainedPalette);
            constrainedColorMap.set(closestColor, (constrainedColorMap.get(closestColor) || 0) + count);
          }

          // Convert back to colors array with RGB values
          colors = Array.from(constrainedColorMap.entries()).map(([colorHex, count]) => {
            const r = parseInt(colorHex.slice(1, 3), 16);
            const g = parseInt(colorHex.slice(3, 5), 16);
            const b = parseInt(colorHex.slice(5, 7), 16);
            return [r, g, b, count];
          });
        }

        // If we already have fewer colors than target, just return them
        if (colors.length <= targetColors) {
          const palette = colors.map(([r, g, b]) =>
            `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`
          );
          resolve(palette);
          return;
        }

        // Median cut algorithm
        const medianCut = (colorList: [number, number, number, number][], depth: number): string[] => {
          if (depth === 0 || colorList.length <= 1) {
            // Calculate average color weighted by frequency
            let totalR = 0, totalG = 0, totalB = 0, totalCount = 0;
            for (const [r, g, b, count] of colorList) {
              totalR += r * count;
              totalG += g * count;
              totalB += b * count;
              totalCount += count;
            }
            const avgR = Math.round(totalR / totalCount);
            const avgG = Math.round(totalG / totalCount);
            const avgB = Math.round(totalB / totalCount);
            return [`#${avgR.toString(16).padStart(2, '0')}${avgG.toString(16).padStart(2, '0')}${avgB.toString(16).padStart(2, '0')}`];
          }

          // Find channel with greatest range
          let minR = 255, maxR = 0, minG = 255, maxG = 0, minB = 255, maxB = 0;
          for (const [r, g, b] of colorList) {
            minR = Math.min(minR, r);
            maxR = Math.max(maxR, r);
            minG = Math.min(minG, g);
            maxG = Math.max(maxG, g);
            minB = Math.min(minB, b);
            maxB = Math.max(maxB, b);
          }

          const rangeR = maxR - minR;
          const rangeG = maxG - minG;
          const rangeB = maxB - minB;

          // Sort by channel with greatest range
          let sortChannel: 0 | 1 | 2 = 0;
          if (rangeG >= rangeR && rangeG >= rangeB) sortChannel = 1;
          else if (rangeB >= rangeR && rangeB >= rangeG) sortChannel = 2;

          colorList.sort((a, b) => a[sortChannel] - b[sortChannel]);

          // Find median by pixel count (not by unique colors)
          const totalPixels = colorList.reduce((sum, c) => sum + c[3], 0);
          let pixelCount = 0;
          let medianIndex = 0;
          for (let i = 0; i < colorList.length; i++) {
            pixelCount += colorList[i][3];
            if (pixelCount >= totalPixels / 2) {
              medianIndex = i + 1;
              break;
            }
          }

          const left = colorList.slice(0, medianIndex);
          const right = colorList.slice(medianIndex);

          return [...medianCut(left, depth - 1), ...medianCut(right, depth - 1)];
        };

        // Calculate depth needed for target colors (2^depth = targetColors)
        const depth = Math.ceil(Math.log2(targetColors));
        let palette = medianCut(colors, depth);

        // Trim to exact target size
        palette = palette.slice(0, targetColors);

        resolve(palette);
      };

      img.onerror = () => reject(new Error('Failed to load image'));
    });
  };

  // Handle palette analysis
  const handleAnalyzePalette = async () => {
    if (!originalImage) return;

    setIsProcessing(true);
    try {
      // Generate platform-specific color space if applicable
      let constrainedPalette: string[] | undefined;

      if (currentPlatform.colorDepth <= 12 || currentPlatform.id === 'atari_st') {
        // For platforms with limited color spaces, constrain to available colors
        constrainedPalette = generatePlatformColorSpace(currentPlatform.colorDepth);
      }

      const palette = await analyzePalette(currentPlatform.paletteSize, constrainedPalette);
      setAnalyzedPalette(palette);
      setShowPaletteAnalyzer(true);
    } catch (error) {
      console.error('Error analyzing palette:', error);
    } finally {
      setIsProcessing(false);
    }
  };

  // Apply analyzed palette to image
  const handleApplyAnalyzedPalette = async () => {
    if (!originalImage || !analyzedPalette) return;

    setIsProcessing(true);
    try {
      const img = new Image();
      img.src = originalImage;

      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });

      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      ctx.drawImage(img, 0, 0);
      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      const data = imageData.data;

      // Convert each pixel to closest palette color
      for (let i = 0; i < data.length; i += 4) {
        const r = data[i];
        const g = data[i + 1];
        const b = data[i + 2];

        const closestColor = findClosestColor(r, g, b, analyzedPalette);

        data[i] = parseInt(closestColor.slice(1, 3), 16);
        data[i + 1] = parseInt(closestColor.slice(3, 5), 16);
        data[i + 2] = parseInt(closestColor.slice(5, 7), 16);
      }

      ctx.putImageData(imageData, 0, 0);
      const processedImage = canvas.toDataURL('image/png');
      setSourceImage(processedImage);
      setShowPaletteAnalyzer(false);
    } catch (error) {
      console.error('Error applying analyzed palette:', error);
    } finally {
      setIsProcessing(false);
    }
  };

  // Fit image to platform screen dimensions
  const handleFitToScreen = async () => {
    if (!originalImage) return;

    setIsProcessing(true);

    try {
      const img = new Image();
      img.src = originalImage; // Always process from original

      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });

      const canvas = document.createElement('canvas');
      canvas.width = currentPlatform.resolution.width;
      canvas.height = currentPlatform.resolution.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      // Draw scaled image
      ctx.imageSmoothingEnabled = false; // Pixel-perfect scaling
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

      const resizedImage = canvas.toDataURL('image/png');
      setSourceImage(resizedImage);
      setOriginalImage(resizedImage); // Update original after resize
      setHeight(currentPlatform.resolution.height);
    } catch (error) {
      console.error('Error fitting to screen:', error);
    } finally {
      setIsProcessing(false);
    }
  };

  const previewWidth = currentPlatform.resolution.width * 2;
  const previewHeight = currentPlatform.resolution.height * 2;
  const clampedHeight = Math.min(height, currentPlatform.resolution.height);

  return (
    <div
      className="dialog-overlay"
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
      }}
      onClick={onClose}
    >
      <div
        className="dialog-content"
        style={{
          backgroundColor: "var(--bg-dark)",
          border: "2px solid var(--green-bright)",
          padding: 24,
          maxWidth: 1200,
          width: "95%",
          maxHeight: "90vh",
          overflow: "auto",
          fontFamily: "'Share Tech Mono', monospace",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{ marginBottom: 24 }}>
          <h2 style={{ color: "var(--green-bright)", margin: 0, marginBottom: 8 }}>
            IMAGE MANAGER
          </h2>
          <p style={{ color: "var(--text-dim)", margin: 0 }}>
            Location: {location.name || `Room ${location.id}`}
          </p>
        </div>

        {/* Platform Selector */}
        <div className="card" style={{ marginBottom: 16 }}>
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label">Target Platform</label>
            <select
              value={selectedPlatform}
              onChange={(e) => setSelectedPlatform(e.target.value as PlatformId)}
              style={{
                display: "block",
                width: "100%",
                padding: 8,
                backgroundColor: "var(--bg-darker)",
                border: "1px solid var(--green-dim)",
                color: "var(--text-primary)",
                fontFamily: "'Share Tech Mono', monospace",
                fontSize: 14,
              }}
            >
              {PLATFORM_LIST.map((platform) => (
                <option key={platform.id} value={platform.id}>
                  {platform.displayName}
                </option>
              ))}
            </select>
            <p style={{ fontSize: 12, color: "var(--text-dim)", marginTop: 4 }}>
              {currentPlatform.resolution.width}×{currentPlatform.resolution.height}px • {currentPlatform.paletteSize} colors
              {currentPlatform.restrictions.description && ` • ${currentPlatform.restrictions.description}`}
            </p>
          </div>
        </div>

        {/* Two-column layout */}
        <div style={{ display: "flex", gap: 24, marginBottom: 16 }}>
          {/* Left column: Preview */}
          <div style={{ flex: "0 0 auto" }}>
          <div
            style={{
              width: previewWidth,
              height: previewHeight,
              backgroundColor: "#000",
              border: "2px solid var(--green-dim)",
              position: "relative",
              margin: "0 auto",
            }}
          >
            {/* Screen area (scaled 2x) */}
            <div
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                width: previewWidth,
                height: previewHeight,
                display: "flex",
                flexDirection: "column",
              }}
            >
              {/* Image area */}
              <div
                style={{
                  flex: `0 0 ${(clampedHeight / currentPlatform.resolution.height) * previewHeight}px`,
                  backgroundColor: "#000",
                  position: "relative",
                  overflow: "hidden",
                }}
              >
                {sourceImage && (
                  <img
                    src={sourceImage}
                    alt="Preview"
                    style={{
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      imageRendering: "pixelated",
                    }}
                  />
                )}
                {!sourceImage && (
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      height: "100%",
                      color: "var(--text-dim)",
                      fontSize: 14,
                    }}
                  >
                    No image selected
                  </div>
                )}
              </div>

              {/* Text/Parser area */}
              <div
                style={{
                  flex: 1,
                  backgroundColor: "#000",
                  padding: 8,
                  fontSize: 12,
                  color: "var(--green-bright)",
                  fontFamily: "monospace",
                  lineHeight: 1.2,
                }}
              >
                <div>&gt; {location.description || "Room description..."}</div>
                <div style={{ marginTop: 8, color: "var(--text-dim)" }}>
                  You can see: ...
                </div>
                <div style={{ marginTop: 8 }}>
                  <span style={{ color: "var(--green-bright)" }}>&gt; </span>
                  <span className="cursor-blink">_</span>
                </div>
              </div>
            </div>

            {/* Dimension overlay */}
            <div
              style={{
                position: "absolute",
                top: 4,
                right: 4,
                backgroundColor: "rgba(0, 0, 0, 0.7)",
                padding: "4px 8px",
                fontSize: 10,
                color: "var(--green-bright)",
                border: "1px solid var(--green-dim)",
              }}
            >
              {currentPlatform.resolution.width}×{currentPlatform.resolution.height} px
            </div>
          </div>

          <div style={{ textAlign: "center", marginTop: 8, fontSize: 12, color: "var(--text-dim)" }}>
            {currentPlatform.displayName} Screen Preview (2x scale)
          </div>
          </div>

          {/* Right column: Controls */}
          <div style={{ flex: 1, minWidth: 300 }}>
        {/* Controls */}
        <div className="card" style={{ marginBottom: 16 }}>
          <div className="form-group">
            <label className="form-label">Image File</label>
            <input
              type="file"
              accept="image/png,image/bmp,image/gif,image/jpeg"
              onChange={handleFileSelect}
              style={{
                display: "block",
                width: "100%",
                padding: 8,
                backgroundColor: "var(--bg-darker)",
                border: "1px solid var(--green-dim)",
                color: "var(--text-primary)",
                fontFamily: "'Share Tech Mono', monospace",
                fontSize: 14,
              }}
            />
            <p style={{ fontSize: 12, color: "var(--text-dim)", marginTop: 4 }}>
              Image will be converted to {currentPlatform.resolution.width}×{clampedHeight}px with {currentPlatform.displayName} palette
            </p>
          </div>

          {/* Image Processing Buttons */}
          {sourceImage && (
            <div className="form-group">
              <label className="form-label">Image Processing</label>
              <div style={{ display: "flex", gap: 8, marginBottom: 8 }}>
                <button
                  className="btn btn-secondary"
                  onClick={handleFitToScreen}
                  disabled={isProcessing}
                  style={{ flex: 1, fontSize: 12, padding: "8px 12px" }}
                >
                  {isProcessing ? "Processing..." : "Fit to Screen"}
                </button>
                <button
                  className="btn btn-secondary"
                  onClick={handleApplyPalette}
                  disabled={isProcessing || !currentPlatform.palette}
                  style={{ flex: 1, fontSize: 12, padding: "8px 12px" }}
                >
                  {isProcessing ? "Processing..." : "Apply Fixed Palette"}
                </button>
              </div>
              {canAnalyzePalette() && (
                <>
                  <button
                    className="btn btn-primary"
                    onClick={handleAnalyzePalette}
                    disabled={isProcessing}
                    style={{ width: "100%", fontSize: 12, padding: "8px 12px", marginBottom: 8 }}
                  >
                    {isProcessing ? "Analyzing..." : `🎨 Analyze Optimal ${currentPlatform.paletteSize}-Color Palette`}
                  </button>
                  <div style={{
                    backgroundColor: "rgba(0, 255, 0, 0.05)",
                    padding: 8,
                    borderRadius: 4,
                    border: "1px solid var(--green-dim)",
                    marginBottom: 8
                  }}>
                    <p style={{ fontSize: 10, color: "var(--green-bright)", margin: 0 }}>
                      {currentPlatform.id === 'atari_st' && "✓ Extracts best 16 colors from 512-color palette"}
                      {currentPlatform.id === 'amiga' && "✓ Extracts best 32 colors from 4096-color palette"}
                      {currentPlatform.id === 'msdos' && "✓ Extracts best 256 colors from 262K-color palette"}
                      {currentPlatform.id.startsWith('amstrad_cpc') && "✓ Selects optimal colors from 27-color palette"}
                    </p>
                  </div>
                </>
              )}
              <p style={{ fontSize: 11, color: "var(--text-dim)", marginTop: 4 }}>
                <strong>Fit to Screen:</strong> Resize to {currentPlatform.resolution.width}×{currentPlatform.resolution.height}px
                {currentPlatform.palette && (
                  <>
                    <br />
                    <strong>Apply Fixed Palette:</strong> Use {currentPlatform.displayName}'s fixed colors
                  </>
                )}
                {canAnalyzePalette() && (
                  <>
                    <br />
                    <strong>Analyze Palette:</strong> Extract image-optimized {currentPlatform.paletteSize} colors
                  </>
                )}
              </p>
            </div>
          )}

          <div className="form-group">
            <label className="form-label">Image Height: {clampedHeight}px</label>
            <input
              type="range"
              min="32"
              max={currentPlatform.resolution.height}
              step="8"
              value={clampedHeight}
              onChange={(e) => setHeight(Number(e.target.value))}
              style={{ width: "100%" }}
            />
            <p style={{ fontSize: 12, color: "var(--text-dim)", marginTop: 4 }}>
              Remaining space for text: {currentPlatform.resolution.height - clampedHeight}px
            </p>
          </div>
        </div>

        {/* Color Palette Reference */}
        {currentPlatform.palette && (
          <div style={{ marginBottom: 24 }}>
            <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 8 }}>
              {currentPlatform.displayName} {canAnalyzePalette() ? 'Reference' : 'Fixed'} Palette ({currentPlatform.paletteSize} colors):
              {canAnalyzePalette() && (
                <span style={{ marginLeft: 8, color: "var(--green-bright)", fontSize: 10 }}>
                  ✓ Palette analysis available
                </span>
              )}
            </div>
            <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
              {currentPlatform.palette.map((color, index) => (
                <div
                  key={index}
                  style={{
                    width: 24,
                    height: 24,
                    backgroundColor: color,
                    border: "1px solid var(--green-dim)",
                  }}
                  title={color}
                />
              ))}
            </div>
            <p style={{ fontSize: 11, color: "var(--text-dim)", marginTop: 8 }}>
              {currentPlatform.restrictions.description}
            </p>
          </div>
        )}
          </div>
        </div>

        {/* Action Buttons */}
        <div style={{ display: "flex", gap: 12, justifyContent: "flex-end" }}>
          {sourceImage && (
            <button
              className="btn btn-secondary"
              onClick={handleRemove}
              style={{ backgroundColor: "var(--red-dark)" }}
            >
              Remove Image
            </button>
          )}
          <button className="btn btn-secondary" onClick={onClose}>
            Cancel
          </button>
          <button className="btn btn-primary" onClick={handleSave}>
            Save
          </button>
        </div>
      </div>

      {/* Palette Analyzer Dialog */}
      {showPaletteAnalyzer && analyzedPalette && (
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: "rgba(0, 0, 0, 0.9)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1100,
          }}
          onClick={() => setShowPaletteAnalyzer(false)}
        >
          <div
            className="card"
            style={{
              maxWidth: 800,
              padding: 24,
              maxHeight: "90vh",
              overflow: "auto",
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <h3 style={{ color: "var(--green-bright)", marginBottom: 16 }}>
              🎨 ANALYZED PALETTE
            </h3>

            <p style={{ color: "var(--text-dim)", marginBottom: 8, fontSize: 14 }}>
              Extracted {analyzedPalette.length} optimal colors from your image using median cut algorithm.
            </p>

            <div style={{
              backgroundColor: "rgba(0, 150, 255, 0.1)",
              padding: 12,
              borderRadius: 4,
              marginBottom: 16,
              border: "1px solid var(--blue-dim)"
            }}>
              <div style={{ fontSize: 12, color: "var(--blue-bright)", marginBottom: 4 }}>
                {currentPlatform.id === 'atari_st' && (
                  <>📊 <strong>Atari ST Mode:</strong> Selected from 512 available colors (9-bit RGB)</>
                )}
                {currentPlatform.id === 'amiga' && (
                  <>📊 <strong>Amiga Mode:</strong> Selected from 4,096 available colors (12-bit RGB)</>
                )}
                {currentPlatform.id === 'msdos' && (
                  <>📊 <strong>MS-DOS VGA Mode:</strong> Selected from 262,144 available colors (18-bit RGB)</>
                )}
                {currentPlatform.id === 'amstrad_cpc_mode0' && (
                  <>📊 <strong>Amstrad CPC Mode 0:</strong> 16 colors selected from 27-color palette</>
                )}
                {currentPlatform.id === 'amstrad_cpc_mode1' && (
                  <>📊 <strong>Amstrad CPC Mode 1:</strong> 4 colors selected from 27-color palette</>
                )}
              </div>
              <p style={{ fontSize: 11, color: "var(--text-dim)", margin: 0 }}>
                This analyzed palette is specifically optimized for your image content and works within
                {' '}{currentPlatform.displayName}'s hardware capabilities.
              </p>
            </div>

            <div style={{ marginBottom: 24 }}>
              <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 12 }}>
                Extracted Palette ({analyzedPalette.length} colors):
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(8, 1fr)", gap: 8 }}>
                {analyzedPalette.map((color, index) => (
                  <div key={index} style={{ textAlign: "center" }}>
                    <div
                      style={{
                        width: "100%",
                        aspectRatio: "1/1",
                        backgroundColor: color,
                        border: "2px solid var(--green-dim)",
                        borderRadius: 4,
                        marginBottom: 4,
                      }}
                    />
                    <div style={{ fontSize: 9, color: "var(--text-dim)", fontFamily: "monospace" }}>
                      {color.toUpperCase()}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {currentPlatform.palette && (
              <div style={{ marginBottom: 24 }}>
                <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 12 }}>
                  For comparison - Fixed {currentPlatform.displayName} Palette:
                </div>
                <div style={{ display: "grid", gridTemplateColumns: "repeat(8, 1fr)", gap: 8 }}>
                  {currentPlatform.palette.slice(0, currentPlatform.paletteSize).map((color, index) => (
                    <div key={index} style={{ textAlign: "center" }}>
                      <div
                        style={{
                          width: "100%",
                          aspectRatio: "1/1",
                          backgroundColor: color,
                          border: "2px solid var(--border-color)",
                          borderRadius: 4,
                          marginBottom: 4,
                        }}
                      />
                      <div style={{ fontSize: 9, color: "var(--text-dim)", fontFamily: "monospace" }}>
                        {color.toUpperCase()}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div style={{ backgroundColor: "rgba(0, 255, 0, 0.05)", padding: 12, borderRadius: 4, marginBottom: 16, border: "1px solid var(--green-dim)" }}>
              <div style={{ fontSize: 12, color: "var(--green-bright)", marginBottom: 8 }}>
                💡 Platform-Specific Recommendations:
              </div>
              <ul style={{ fontSize: 11, color: "var(--text-dim)", marginLeft: 20, lineHeight: 1.6, marginBottom: 0 }}>
                <li><strong>Atari ST:</strong> Analyzed palette highly recommended! Extracts optimal 16 colors from 512 possibilities</li>
                <li><strong>Amiga:</strong> Analyzed palette produces superior results with 32 colors from 4096</li>
                <li><strong>MS-DOS VGA:</strong> Analyzed palette significantly improves image quality with 256 optimized colors</li>
                <li><strong>Amstrad CPC:</strong> Analyzed palette selects best colors from the 27-color hardware palette</li>
                <li><strong>Fixed palette systems</strong> (ZX Spectrum, C64, MSX): Use "Apply Fixed Palette" instead</li>
              </ul>
            </div>

            <div style={{ display: "flex", gap: 12, justifyContent: "flex-end" }}>
              <button
                className="btn btn-secondary"
                onClick={() => setShowPaletteAnalyzer(false)}
              >
                Cancel
              </button>
              <button
                className="btn btn-primary"
                onClick={handleApplyAnalyzedPalette}
                disabled={isProcessing}
              >
                {isProcessing ? "Applying..." : "Apply This Palette"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
